NormalSeed/JointCoopProject

- JointCoopProject/.vsconfig
- JointCoopProject/Assets/Settings/Renderer2D.asset
- JointCoopProject/ProjectSettings/ProjectSettings.asset
- JointCoopProject/ProjectSettings/SceneTemplateSettings.json
> [Setting] 2D RoguelikeGame Project Start

- JointCoopProject/Assets/KGW/Materials.meta
- JointCoopProject/Assets/KGW/Materials/TearMaterial.mat
- JointCoopProject/Assets/KGW/Materials/TearMaterial.mat.meta
- JointCoopProject/Assets/KGW/Prefabs.meta
- JointCoopProject/Assets/KGW/Prefabs/Tear.prefab
- JointCoopProject/Assets/KGW/Prefabs/Tear.prefab.meta
- JointCoopProject/Assets/KGW/Scripts.meta
- JointCoopProject/Assets/KGW/Scripts/IsaacMovement.cs
- JointCoopProject/Assets/KGW/Scripts/IsaacMovement.cs.meta
- JointCoopProject/Assets/KGW/Scripts/IsaacStatus.cs
- JointCoopProject/Assets/KGW/Scripts/IsaacStatus.cs.meta
- JointCoopProject/Assets/KGW/Scripts/IsaacTearController.cs
- JointCoopProject/Assets/KGW/Scripts/IsaacTearController.cs.meta
- JointCoopProject/Assets/KGW/TestScene.unity
- JointCoopProject/Assets/KGW/TestScene.unity.meta
- JointCoopProject/ProjectSettings/InputManager.asset
- JointCoopProject/ProjectSettings/QualitySettings.asset
입력에 대한 아이작의 움직임 구현 (가속, 감속하여 움직임 구현)
> [Feat] Isaac Movement Implement

- JointCoopProject/Assets/KGW/Materials/SwordMaterial.mat
- JointCoopProject/Assets/KGW/Materials/SwordMaterial.mat.meta
- JointCoopProject/Assets/KGW/Prefabs/Sword.prefab
- JointCoopProject/Assets/KGW/Prefabs/Sword.prefab.meta
- JointCoopProject/Assets/KGW/Prefabs/Tear.prefab
- JointCoopProject/Assets/KGW/Scripts/IDamagable.cs
- JointCoopProject/Assets/KGW/Scripts/IDamagable.cs.meta
- JointCoopProject/Assets/KGW/Scripts/PlayerMovement.cs
- JointCoopProject/Assets/KGW/Scripts/PlayerStatus.cs
- JointCoopProject/Assets/KGW/Scripts/PlayerSwordController.cs
- JointCoopProject/Assets/KGW/Scripts/PlayerSwordController.cs.meta
- JointCoopProject/Assets/KGW/Scripts/PlayerTearController.cs
- JointCoopProject/Assets/KGW/TestScene.unity
> [Feat] Player Sword Attack Motion 1/2 Implement

- JointCoopProject/Assets/KGW/AnimationController/PlayerAnimationController.controller
- JointCoopProject/Assets/KGW/AnimationController/PlayerAnimators/Knight-Block.png.meta
- JointCoopProject/Assets/KGW/AnimationController/PlayerAnimators/Knight-Death.png.meta
- JointCoopProject/Assets/KGW/AnimationController/PlayerAnimators/Knight-Hurt.png.meta
- JointCoopProject/Assets/KGW/AnimationController/PlayerAnimators/Knight-Idle.png.meta
- JointCoopProject/Assets/KGW/AnimationController/PlayerAnimators/Knight-Walk.png.meta
- JointCoopProject/Assets/KGW/AnimationController/PlayerDeath.anim
- JointCoopProject/Assets/KGW/AnimationController/PlayerHurt.anim
- JointCoopProject/Assets/KGW/Scripts/IDamagable.cs
- JointCoopProject/Assets/KGW/Scripts/MonsterTest.cs
- JointCoopProject/Assets/KGW/Scripts/PlayerMovement.cs
- JointCoopProject/Assets/KGW/Scripts/PlayerStatus.cs
- JointCoopProject/Assets/KGW/Scripts/PlayerSwordController.cs
- JointCoopProject/Assets/KGW/TestScene.unity
플레이어가 피격 시 넉백과 애니메이션 추가, 무적시간 구현
> [Feat] Add Player Hit Knock Back

- JointCoopProject/Assets/LGH/Prefabs.meta
- JointCoopProject/Assets/LGH/Prefabs/Orc.prefab
- JointCoopProject/Assets/LGH/Prefabs/Orc.prefab.meta
- JointCoopProject/Assets/LGH/Scripts/Monster/MonsterBase.cs
- JointCoopProject/Assets/LGH/Scripts/Monster/MonsterModel.cs
- JointCoopProject/Assets/LGH/Scripts/Monster/MonsterMovement.cs
- JointCoopProject/Assets/LGH/Scripts/Monster/MonsterState.cs
- JointCoopProject/Assets/LGH/Scripts/Monster/MonsterView.cs
- JointCoopProject/Assets/LGH/Scripts/Monster/Orc/Animation/Orc_Attack1.anim
- JointCoopProject/Assets/LGH/Scripts/Monster/Orc/Animation/Orc_Dead.anim
- JointCoopProject/Assets/LGH/Scripts/Monster/Orc/Animation/Orc_Dead.anim.meta
- JointCoopProject/Assets/LGH/Scripts/Monster/Orc/Animation/Orc_Hurt.anim
- JointCoopProject/Assets/LGH/Scripts/Monster/Orc/Animation/Orc_Hurt.anim.meta
- JointCoopProject/Assets/LGH/Scripts/Monster/Orc/OrcAnimationController.controller
- JointCoopProject/Assets/LGH/Scripts/Monster/Orc/OrcAttack1.cs
- JointCoopProject/Assets/LGH/Scripts/Monster/Orc/OrcAttack1.cs.meta
- JointCoopProject/Assets/LGH/Scripts/Monster/Orc/OrcController.cs
- JointCoopProject/Assets/LGH/Scripts/Monster/Orc/OrcState.cs
- JointCoopProject/Assets/LGH/Scripts/StateMachine/BaseState.cs
- JointCoopProject/Assets/LGH/Scripts/Test/TestPlayer.cs
- JointCoopProject/Assets/LGH/Test/TestScene.unity
Orc 몬스터 기능 구현 및 애니메이션 적용
Item Drop 제외 구현 완료
> LGH/Monster(Orc)Additional Work

- JointCoopProject/Assets/LGH/Scripts/Monster/Orc/OrcController.cs
> [Chore] Orc annotation add

- JointCoopProject/Assets/KGW/AnimationController/PlayerAnimators/PlayerAnimationController.controller
- JointCoopProject/Assets/KGW/AnimationController/PlayerAnimators/Player_Down_Attack.anim
- JointCoopProject/Assets/KGW/AnimationController/PlayerAnimators/Player_Down_Attack.anim.meta
- JointCoopProject/Assets/KGW/AnimationController/PlayerAnimators/Player_Left_Attack.anim
- JointCoopProject/Assets/KGW/AnimationController/PlayerAnimators/Player_Left_Attack.anim.meta
- JointCoopProject/Assets/KGW/AnimationController/PlayerAnimators/Player_Right_Attack.anim
- JointCoopProject/Assets/KGW/AnimationController/PlayerAnimators/Player_Right_Attack.anim.meta
- JointCoopProject/Assets/KGW/AnimationController/PlayerAnimators/Player_Up_Attack.anim
- JointCoopProject/Assets/KGW/AnimationController/PlayerAnimators/Player_Up_Attack.anim.meta
- JointCoopProject/Assets/KGW/Scripts/PlayerMovement.cs
- JointCoopProject/Assets/KGW/TestScene.unity
플레이어의 공격 애니메이션 및 대쉬 동작 중 플레이어가 반투명화가 되도록 수정
> [Feat] Add Player Attack Animation

- JointCoopProject/Assets/USW/ProtoType/Scene/New Scene.unity
- JointCoopProject/Assets/USW/Script/MapGenerator/MinimapManager.cs
- JointCoopProject/Assets/USW/Script/MapGenerator/UI_ShadowMinimap.prefab
- JointCoopProject/Assets/USW/Script/MapGenerator/UI_ShadowMinimap.prefab.meta
[Create]MiniMap Generator map 연동 작업
> [Create]MiniMap Generator map 연동 구현

- JointCoopProject/Assets/KGW/AnimationController/FortuneCatAnimators.meta
- JointCoopProject/Assets/KGW/AnimationController/FortuneCatAnimators/FortuneCatAnimationController.controller
- JointCoopProject/Assets/KGW/AnimationController/FortuneCatAnimators/FortuneCatAnimationController.controller.meta
- JointCoopProject/Assets/KGW/AnimationController/FortuneCatAnimators/FortuneCat_Idle.anim
- JointCoopProject/Assets/KGW/AnimationController/FortuneCatAnimators/FortuneCat_Idle.anim.meta
- JointCoopProject/Assets/KGW/Prefabs/CrystalBall.prefab
- JointCoopProject/Assets/KGW/Prefabs/CrystalBall.prefab.meta
- JointCoopProject/Assets/KGW/Prefabs/FortuneCat.prefab
- JointCoopProject/Assets/KGW/Prefabs/FortuneCat.prefab.meta
- JointCoopProject/Assets/KGW/Scripts/Commonness/IBuff.cs
- JointCoopProject/Assets/KGW/Scripts/Fortune Teller/AttackPower_Buff.cs
- JointCoopProject/Assets/KGW/Scripts/Fortune Teller/AttackSpeed_Buff.cs
- JointCoopProject/Assets/KGW/Scripts/Fortune Teller/BuffCreateFactory.cs
- JointCoopProject/Assets/KGW/Scripts/Fortune Teller/BuffManager.cs
- JointCoopProject/Assets/KGW/Scripts/Fortune Teller/CrystalBallController.cs
- JointCoopProject/Assets/KGW/Scripts/Fortune Teller/MoveSpeed_Buff.cs
- JointCoopProject/Assets/KGW/Scripts/Fortune Teller/Nothing_Buff.cs
- JointCoopProject/Assets/KGW/Scripts/Fortune Teller/TodayFortune_Buff.cs
- JointCoopProject/Assets/KGW/Scripts/Player/PlayerMovement.cs
- JointCoopProject/Assets/KGW/Scripts/Player/PlayerStatus.cs
- JointCoopProject/Assets/KGW/Scripts/Player/PlayerSwordController.cs
- JointCoopProject/Assets/KGW/TestScene.unity
점술사를 추가하여 플레이어 스텟 퍼버 시스템 3/5구현
> [Feat] Add BuffSystem 3/5

- JointCoopProject/Assets/LGH/Scripts/Monster/MonsterBase.cs
- JointCoopProject/Assets/Skill.meta
- JointCoopProject/Assets/USW/ProtoType/PlayerSkill/New Laser Skill SO.asset.meta
- JointCoopProject/Assets/USW/ProtoType/Scene/MapGenerator.unity
- JointCoopProject/Assets/USW/Script/MapGenerator/CameraController.cs
- JointCoopProject/Assets/USW/Script/MapGenerator/MapGenerator.cs
- JointCoopProject/Assets/USW/Script/MapGenerator/RoomMonsterManager.cs
- JointCoopProject/Assets/USW/Script/MapGenerator/RoomMonsterManager.cs.meta
[Feature] 인접 노드에 따른 스프라이트 배치 
[Chore] 카메라 컨트롤러 x값 조정
[Feature] 플레이어가 방을 이동함에 따라 몬스터 SetActive
> [Feature] 인접 노드에 따른 스프라이트 배치 

- JointCoopProject/Assets/USW/Script/BossRoomLadderManager.cs
> [chore] 컴파일에러 수정

- JointCoopProject/Assets/CYE/Prefabs/ItemSample01.prefab
- JointCoopProject/Assets/CYE/Scenes/ItemTest01.unity
- JointCoopProject/Assets/CYE/Scripts/Items/Expend/Bomb.cs
- JointCoopProject/Assets/CYE/Scripts/Items/Expend/Coin.cs
- JointCoopProject/Assets/CYE/Scripts/Items/ItemTestPlayerController.cs
- JointCoopProject/Assets/CYE/Scripts/Items/S/GameItem.cs
- JointCoopProject/Assets/CYE/Scripts/SlotMachine/SlotMachine.cs
***
1. 컴파일 에러 제거
2. 샘플 아이템 태그 추가
> [Fix] Fix Compile Error

- JointCoopProject/Assets/USW/ProtoType/PlayerSkill/PlayerSkillManager.cs
- JointCoopProject/Assets/USW/Scene/Real_Stage1.unity
- JointCoopProject/Assets/USW/Scene/Real_Stage7.unity
- JointCoopProject/Assets/USW/Scene/Real_Stage7.unity.meta
- JointCoopProject/Assets/USW/Script/BossRoomLadderManager.cs
- JointCoopProject/Assets/USW/Script/MapGenerator/MapGenerator.cs
- JointCoopProject/Assets/USW/Script/MapGenerator/PlayerRoomMovement.cs
> [chore]merge 전 통합 

- JointCoopProject/Assets/LGH/Prefabs/SoundManager.meta
- JointCoopProject/Assets/LGH/Prefabs/SoundManager/SoundManager.prefab
- JointCoopProject/Assets/LGH/Prefabs/SoundManager/SoundManager.prefab.meta
- JointCoopProject/Assets/LGH/Scripts/Manager.meta
- JointCoopProject/Assets/LGH/Scripts/Manager/SoundManager.cs
- JointCoopProject/Assets/LGH/Scripts/Manager/SoundManager.cs.meta
- JointCoopProject/Assets/LGH/Scripts/Test/SoundTester.cs
- JointCoopProject/Assets/LGH/Scripts/Test/SoundTester.cs.meta
- JointCoopProject/Assets/LGH/Scripts/Test/TestSingleton.cs
- JointCoopProject/Assets/LGH/Scripts/Test/TestSingleton.cs.meta
- JointCoopProject/Assets/LGH/Test/TestPrototype.unity
- JointCoopProject/Assets/LGH/Test/TestScene.unity
> LGH/Sound Manager

- JointCoopProject/Assets/KGW/Scripts/Audio/AudioController.cs
- JointCoopProject/Assets/KGW/Scripts/Managers/GameSceneManager.cs
- JointCoopProject/Assets/USW/Scene/Real_Stage2.unity
- JointCoopProject/Assets/USW/Scene/Real_Stage2.unity.meta
- JointCoopProject/Assets/USW/Scene/Real_Stage3.unity
- JointCoopProject/Assets/USW/Scene/Real_Stage3.unity.meta
- JointCoopProject/Assets/USW/Scene/Real_Stage4.unity
- JointCoopProject/Assets/USW/Scene/Real_Stage4.unity.meta
- JointCoopProject/Assets/USW/Scene/Real_Stage5.unity
- JointCoopProject/Assets/USW/Scene/Real_Stage5.unity.meta
- JointCoopProject/Assets/USW/Scene/Real_Stage6.unity
- JointCoopProject/Assets/USW/Scene/Real_Stage6.unity.meta
- JointCoopProject/Assets/USW/Script/BossRoomLadderManager.cs
> [Chore] 기획분들께 넘겨주기전 Scene 배치 작업 

- JointCoopProject/Assets/LGH/Prefabs/SoundManager/SoundManager.prefab
- JointCoopProject/Assets/LGH/Prefabs/Warrior.prefab
- JointCoopProject/Assets/LGH/Scripts/Monster/Warrior/Animations/Warrior_Attack2.anim
- JointCoopProject/Assets/LGH/Scripts/Monster/Warrior/Attack2Mesh.cs
- JointCoopProject/Assets/LGH/Scripts/Monster/Warrior/Attack2Mesh.cs.meta
- JointCoopProject/Assets/LGH/Scripts/Monster/Warrior/WarriorController.cs
- JointCoopProject/Assets/LGH/Test/TestScene.unity
Warrior Attack2 데미지 로직, Attack2 범위 부채꼴 모양 Mesh Renderer 구현
> LGH/Monster Sound

- JointCoopProject/Assets/LSH/Stage_1/Stage_1_Prefab/Room_1_Battle_10.prefab
- JointCoopProject/Assets/LSH/Stage_1/Stage_1_Prefab/Room_1_Battle_12.prefab
- JointCoopProject/Assets/LSH/Stage_1/Stage_1_Prefab/Room_1_Battle_13.prefab
- JointCoopProject/Assets/LSH/Stage_1/Stage_1_Prefab/Room_1_Battle_14.prefab
- JointCoopProject/Assets/LSH/Stage_1/Stage_1_Prefab/Room_1_Battle_15.prefab
- JointCoopProject/Assets/LSH/Stage_1/Stage_1_Prefab/Room_1_Battle_16.prefab
- JointCoopProject/Assets/LSH/Stage_1/Stage_1_Prefab/Room_1_Battle_17.prefab
- JointCoopProject/Assets/LSH/Stage_1/Stage_1_Prefab/Room_1_Battle_18.prefab
- JointCoopProject/Assets/LSH/Stage_1/Stage_1_Prefab/Room_1_Battle_20.prefab
- JointCoopProject/Assets/LSH/Stage_1/Stage_1_Prefab/Room_1_Battle_3.prefab
- JointCoopProject/Assets/LSH/Stage_1/Stage_1_Prefab/Room_1_Battle_4.prefab
- JointCoopProject/Assets/LSH/Stage_1/Stage_1_Prefab/Room_1_Battle_5.prefab
- JointCoopProject/Assets/LSH/Stage_1/Stage_1_Prefab/Room_1_Battle_8.prefab
- JointCoopProject/Assets/LSH/Stage_1/Stage_1_Prefab/Room_1_Battle_9.prefab
> 가시트랩 타일 리지드바디 수정

- JointCoopProject/Assets/LSH/Stage_1/Stage_1_Prefab/Room_1_Battle_19.prefab
> 스테이지 1 19번방 스켈레톤 위치 수정

- JointCoopProject/Assets/KGW/AnimationController/PlayerAnimators/PlayerDeath.anim
- JointCoopProject/Assets/KGW/Scenes/Real_DeathScene.unity
- JointCoopProject/Assets/KGW/Scenes/Real_DeathScene.unity.meta
- JointCoopProject/Assets/KGW/Scenes/Rear_InGame.unity
- JointCoopProject/Assets/KGW/Scripts/MainMenuScripts/MainMenuController.cs
- JointCoopProject/Assets/KGW/Scripts/Managers/UIManager.cs
- JointCoopProject/Assets/KGW/Scripts/Player/PlayerHeartController.cs
- JointCoopProject/Assets/KGW/Scripts/Player/PlayerMovement.cs
플레이어가 죽은 후 메인메뉴 버튼을 클릭하면 에디터 정지 버그 확인 UIManager에서 Button의 리스너가 프레임마다 추가되어 정지 확인으로 코드 수정
> [Fix] On Death Panel MainMenu Button Error

- JointCoopProject/Assets/KGW/AnimationController/PlayerAnimators/PlayerAnimationController.controller
- JointCoopProject/Assets/KGW/AnimationController/PlayerAnimators/PlayerDeath.anim
- JointCoopProject/Assets/KGW/Prefabs/AttackBlade.prefab
- JointCoopProject/Assets/KGW/Prefabs/DaggerBlade.prefab
- JointCoopProject/Assets/KGW/Prefabs/DaggerBlade.prefab.meta
- JointCoopProject/Assets/KGW/Prefabs/SwordEnergy 1.prefab
- JointCoopProject/Assets/KGW/Prefabs/SwordEnergy 1.prefab.meta
- JointCoopProject/Assets/KGW/Scenes/Real_CutScene.unity
- JointCoopProject/Assets/KGW/Scripts/MainMenuScripts/MainMenuController.cs
- JointCoopProject/Assets/KGW/Scripts/Managers/UIManager.cs
단검, 검기, 칼날 프리펩의 스프라이트가 None으로 되는 버그로 인하여 빈오브젝트에서 뺀 후 다시 프리팹 생성
> [Fix] Dagger, SwordEnergy, AttackBlade Re Prefab

- JointCoopProject/Assets/LGH/Scripts/Monster/Dragon/DragonController.cs
- JointCoopProject/Assets/LGH/Scripts/Monster/GoblinKing/GoblinKingController.cs
- JointCoopProject/Assets/LGH/Scripts/Monster/Gollux/GolluxController.cs
- JointCoopProject/Assets/LGH/Scripts/Monster/Incubus/IncubusController.cs
- JointCoopProject/Assets/LGH/Scripts/Monster/MonsterBase.cs
- JointCoopProject/Assets/LGH/Scripts/Monster/ShardSlayer/ShardSlayerController.cs
- JointCoopProject/Assets/LGH/Scripts/Monster/StrayCat/StrayCatController.cs
- JointCoopProject/Assets/LGH/Scripts/Monster/Warrior/WarriorController.cs
각 보스 몬스터들이 활성화 상태가 됐을 때 보스방 BGM이 재생되게 하고 죽었을 때 해당 보스 스테이지 음악이 재생되는 기능 추가
> [Feat] Boss Stage BGM Play

- JointCoopProject/Assets/KGW/Prefabs/CrystalBall.prefab
- JointCoopProject/Assets/KGW/Prefabs/UiPrefab/Inventory_Window.prefab
- JointCoopProject/Assets/KGW/Prefabs/UiPrefab/SceneManager.prefab
- JointCoopProject/Assets/KGW/Prefabs/UiPrefab/SceneManager.prefab.meta
- JointCoopProject/Assets/KGW/Scenes/Real_CutScene.unity
- JointCoopProject/Assets/KGW/Scenes/Real_MainMenu.unity
- JointCoopProject/Assets/KGW/Scenes/Rear_InGame.unity
- JointCoopProject/Assets/KGW/Scripts/Audio/AudioController.cs
- JointCoopProject/Assets/KGW/Scripts/Fortune Teller/CrystalBallController.cs
- JointCoopProject/Assets/KGW/Scripts/MainMenuScripts/MainMenuController.cs
- JointCoopProject/Assets/KGW/Scripts/Managers/GameSceneManager.cs
- JointCoopProject/Assets/KGW/Scripts/Managers/UIManager.cs
- JointCoopProject/Assets/KGW/Scripts/Player/PlayerMovement.cs
- JointCoopProject/Assets/KGW/Videos/AudioMixer.mixer
- JointCoopProject/Assets/KGW/Videos/AudioMixer.mixer.meta
- JointCoopProject/Assets/USW/Scene/ChangeSceneManager.cs
컷씬, 타이틀씬, 인게임씬, 점술사와 상점방 BGM 구현
> [Feat] Add Cut, Title, InGame, Fortune, Shop BGM

- JointCoopProject/Assets/USW/Scene/Real_Stage1.unity
- JointCoopProject/Assets/USW/Scene/Real_Stage2.unity
- JointCoopProject/Assets/USW/Scene/Real_Stage3.unity
- JointCoopProject/Assets/USW/Scene/Real_Stage4.unity
- JointCoopProject/Assets/USW/Scene/Real_Stage5.unity
- JointCoopProject/Assets/USW/Scene/Real_Stage6.unity
- JointCoopProject/Assets/USW/Scene/Real_Stage7.unity
> [Chore] All Stage UIManager Change

- JointCoopProject/Assets/LGH/Scripts/Monster/MonsterBase.cs
- JointCoopProject/Assets/LGH/Scripts/Monster/MonsterMovement.cs
- JointCoopProject/Assets/LGH/Scripts/Monster/MonsterState.cs
- JointCoopProject/Assets/LGH/Scripts/StateMachine/BaseState.cs
- JointCoopProject/ProjectSettings/TagManager.asset
몬스터가 일부 Active 스킬에 피격당하면 3초간 멈추는 상태인 Paralyze 상태 구현
> [Feat] Monster Paralyze

- JointCoopProject/Assets/LSH/Stage_1/Stage_1_Prefab/Room_1_Item.prefab
- JointCoopProject/Assets/LSH/Stage_1/Stage_1_Prefab/Room_1_Secret.prefab
- JointCoopProject/Assets/LSH/Stage_2/Stage_2_Prefab/Room_2_Item.prefab
- JointCoopProject/Assets/LSH/Stage_2/Stage_2_Prefab/Room_2_Secret.prefab
- JointCoopProject/Assets/LSH/Stage_3/Stage_3_Prefab/Room_3_Item.prefab
- JointCoopProject/Assets/LSH/Stage_3/Stage_3_Prefab/Room_3_Secret.prefab
아이템 스포너 갯수 비밀방, 아이템방에 하나씩으로 수정
> [Fix] ItemSpawner Quantity

- JointCoopProject/Assets/CYE/Prefabs/SO/Skill/Passive/Flame/FlameSkillG1SO.asset
- JointCoopProject/Assets/CYE/Prefabs/SO/Skill/Passive/Flame/FlameSkillG2SO.asset
- JointCoopProject/Assets/CYE/Prefabs/SO/Skill/Passive/Flame/FlameSkillG3SO.asset
- JointCoopProject/Assets/CYE/Prefabs/SO/Skill/Passive/Flame/FlameSkillG4SO.asset
- JointCoopProject/Assets/CYE/Prefabs/SO/Skill/Passive/Flame/FlameSkillG5SO.asset
***
1. flame 스킬 데이터 SO의 스킬 프리팹 지정 변경
> [Fix] Flame 스킬 프리팹 지정 변경

- JointCoopProject/Assets/KGW/Prefabs/Player.prefab
- JointCoopProject/Assets/LGH/Player Physics Material 2D.physicsMaterial2D
- JointCoopProject/Assets/LGH/Player Physics Material 2D.physicsMaterial2D.meta
- JointCoopProject/Assets/LGH/Test/TestScene.unity
플레이어에 Physics Material2D 추가해서 끼임 방지
> [Fix] Player Physics Material2D

- JointCoopProject/Assets/KGW/Prefabs/CrystalBall.prefab
- JointCoopProject/Assets/KGW/Scenes/Rear_InGame.unity
- JointCoopProject/Assets/KGW/Scripts/Managers/PlayerStatManager.cs
- JointCoopProject/Assets/KGW/Scripts/Player/PlayerHeartController.cs
플레이어의 체력 값 수정 및 플레이어 스텟 랜덤성 추가
> [Feat] Player Hp Value Change, Player Stat Random

- JointCoopProject/Assets/USW/Scene/Real_Stage1.unity
- JointCoopProject/Assets/USW/Scene/Real_Stage2.unity
- JointCoopProject/Assets/USW/Scene/Real_Stage3.unity
- JointCoopProject/Assets/USW/Scene/Real_Stage4.unity
- JointCoopProject/Assets/USW/Scene/Real_Stage5.unity
- JointCoopProject/Assets/USW/Scene/Real_Stage6.unity
> [Fix] Stage Setting

- JointCoopProject/Assets/LGH/Scripts/Monster/Dragon/DragonFlameController.cs
- JointCoopProject/Assets/LGH/Scripts/Monster/InfectedGoblin/InfectedGoblinFireController.cs
몬스터 투사체 속도(Dragon, InfectedGoblin) 조정
> [Fix] Monster Projectile Spd

- JointCoopProject/Assets/USW/ProtoType/PlayerSkill/SkillData/LaserProjectile.cs
> [Fix] 레이저 enemy레이어 누락

- JointCoopProject/Assets/LSH/Stage_1/Stage_1_Prefab/Room_1_Boss_1.prefab
- JointCoopProject/Assets/LSH/Stage_1/Stage_1_Prefab/Room_1_Boss_2.prefab
- JointCoopProject/Assets/LSH/Stage_2/Stage_2_Prefab/Room_2_Boss_1.prefab
- JointCoopProject/Assets/LSH/Stage_2/Stage_2_Prefab/Room_2_Boss_2.prefab
- JointCoopProject/Assets/LSH/Stage_3/Stage_3_Prefab/Room_3_Boss_1.prefab
- JointCoopProject/Assets/LSH/Stage_3/Stage_3_Prefab/Room_3_Boss_2.prefab
> [Fix] HotFix

- JointCoopProject/Assets/KGW/Prefabs/Player.prefab
- JointCoopProject/Assets/LSH/Stage_1/Stage_1_Prefab/Room_1_Battle_2.prefab
- JointCoopProject/Assets/USW/Script/Spike/SpikeDamage.cs
- JointCoopProject/ProjectSettings/TagManager.asset
[Fix] 플레이어 콜라이더 스파이크전용 콜라이더 구현
> [Fix] 플레이어 콜라이더 스파이크전용 콜라이더 구현

- JointCoopProject/Assets/KGW/Scripts/Fortune Teller/CrystalBallController.cs
- JointCoopProject/Assets/KGW/Scripts/Managers/UIManager.cs
- JointCoopProject/Assets/KGW/Scripts/PlayerPassiveSkills/AttackRange/AttackRange.cs
공격 사거리 강화 리셋 안되는 버그와 점술사 이용 시 골드 미사용 수정
> [Fix] Attack Range Scale Reset Error, Fortune Use Coin

- JointCoopProject/Assets/CYE/Scripts/Manager/InventoryManager.cs
- JointCoopProject/Assets/USW/Scene/ChangeSceneManager.cs
***
1. 인벤토리 초기화 함수 호출부분 수정
2. 초기자금 30골드로 수정
> [Fix] Add Initial coin count

- JointCoopProject/Assets/KGW/Scripts/MainMenuScripts/OptionUIController.cs
> [Fix] Main Menu Resolustion Duplication Error
